apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unipro-site.fullname" . }}
  labels:
    {{- include "unipro-site.labels" . | nindent 4 }}

spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "unipro-site.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      labels:
        {{- include "unipro-site.selectorLabels" . | nindent 8 }}

        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: unipro-site

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          {{- if .Values.env }}
          envFrom:
            - configMapRef:
                name: {{ include "unipro-site.fullname" . }}-env
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /
              port: http

          livenessProbe:
            httpGet:
              path: /
              port: http

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}