{{- if .Values.gateway.enabled }}

{{/*
Production only:
uniproject.jp -> https://www.uniproject.jp
*/}}
{{- if and (not .Values.preview.enabled) .Values.gateway.production.redirectApex }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "unipro-site.fullname" . }}-redirect-to-www
  labels:
    {{- include "unipro-site.labels" . | nindent 4 }}

spec:
  parentRefs:
    - name: {{ .Values.gateway.production.name }}
      namespace: {{ .Values.gateway.production.namespace }}

  hostnames:
    - {{ .Values.gateway.production.apexHostname | quote }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: {{ .Values.gateway.production.hostname | quote }}
            statusCode: 301
{{- end }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "unipro-site.fullname" . }}

  labels:
    {{- include "unipro-site.labels" . | nindent 4 }}

  {{- if .Values.preview.enabled }}
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  {{- end }}

spec:
  parentRefs:
    {{- if .Values.preview.enabled }}
    - name: {{ .Values.gateway.preview.name }}
      namespace: {{ .Values.gateway.preview.namespace }}
    {{- else }}
    - name: {{ .Values.gateway.production.name }}
      namespace: {{ .Values.gateway.production.namespace }}
    {{- end }}

  hostnames:
    {{- if .Values.preview.enabled }}
    - {{ .Values.gateway.preview.hostname | quote }}
    {{- else }}
    - {{ .Values.gateway.production.hostname | quote }}
    {{- end }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: {{ include "unipro-site.fullname" . }}
          port: {{ .Values.service.port }}

      {{- if and (not .Values.preview.enabled) .Values.gateway.production.sessionPersistence.enabled }}
      sessionPersistence:
        sessionName: {{ .Values.gateway.production.sessionPersistence.sessionName }}
        type: Cookie
        cookieConfig:
          lifetimeType: {{ .Values.gateway.production.sessionPersistence.lifetimeType }}
      {{- end }}

{{- end }}