apiVersion: v1
kind: ServiceAccount
metadata:
  name: unipro-site-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unipro-site
spec:
  selector:
    matchLabels:
      app: unipro-site
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "boardmember"
        vault.hashicorp.com/agent-inject-secret-config.txt: "kv-system/data/unipro-site/config"
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{- with secret "kv-system/data/unipro-site/config" -}}
          DISCORD_BOT_TOKEN={{ .Data.data.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID={{ .Data.data.DISCORD_GUILD_ID }}
          DISCORD_TARGET_ROLE_ID={{ .Data.data.DISCORD_TARGET_ROLE_ID }}
          {{- end }}
      labels:
        app: unipro-site
    spec:
      containers:
        - name: app
          image: registry.uniproject.jp/official/unipro-site:4.1.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: default-port
          resources:
            requests:
              cpu: 500m # 必要最低限の0.5CPUを確保
              memory: 1Gi # 必要最低限の1GiBを確保
            limits:
              cpu: 1
              memory: 2Gi # 最大2GiBまで使用可能
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            httpGet:
              path: /
              port: default-port
              httpHeaders:
                - name: X-k8s-Header
                  value: readiness
          env:
            - name: TZ
              value: Asia/Tokyo
      serviceAccountName: unipro-site-sa
      imagePullSecrets:
        - name: internal-harbor
