name: Approve Preview

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  approve:
    if: >
      github.event.issue.pull_request &&
      github.event.comment.body == '/preview'

    uses: UniPro-tech/PreviewHelper/.github/workflows/approve-environment.yml@676d08929777cb2d88bb461ee8352ba3e7f61f3a # v0.1.1

    with:
      approve-environment: Preview

      approvers: '["boardmember"]'

    secrets: inherit
