name: Docker Build and Push
on:
  push:
    tags:
      - 'v*'

jobs:
  # Job 1: Docker setup and build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract tag name
        run: |
          tagname=${GITHUB_REF#refs/*/} && echo "TAG_NAME=${tagname#v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Insecure Registries
        run: |
          SW_JSON=""
          SW_JSON="$(sudo cat /etc/docker/daemon.json | jq '.+{ "insecure-registries":["${{ secrets.K8S_DOCKER_REGISTHOST }}"] }')"
          echo "${SW_JSON}" | sudo bash -c 'cat -- > /etc/docker/daemon.json'
          sudo systemctl restart docker || sudo journalctl -xeu docker.service

      - name: Insecure Setting
        run: |
          export DOCKER_CLIENT_TIMEOUT=120
          export COMPOSE_HTTP_TIMEOUT=120
          sudo systemctl daemon-reload
          sudo systemctl restart docker

      - name: Build Docker image
        run: docker build -t ${{ secrets.K8S_DOCKER_REGISTHOST }}/unipro-site:${{ env.TAG_NAME }} .

      - name: Upload artifact for next job
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: .
  
  # Job 2: Push Docker image
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Push Docker image
        run: docker push ${{ secrets.K8S_DOCKER_REGISTHOST }}/unipro-site:${{ env.TAG_NAME }}